### ISSUE TITLE
Failed provisioning because of usage of mutual exlusive pip arguments 'executable' and 'virtualenv'

### ISSUE THREAD

**Issue by dpratter** [fdemmer/ansible_roles#3]
ATM ansible-local provisioning fails during "update pip" task with the following error message:

`
TASK [python : update pip] *****************************************************
task path: /etc/ansible/roles/python/tasks/20-virtualenv.yml:10
failed: [default] (item=pip==8.1.0) => {"failed": true, "item": "pip==8.1.0", "msg": "parameters are mutually exclusive: ['executable', 'virtualenv']"}
`

It seems that since ansible 2.1.0 it is not possible to use pip arguments  'executable' and 'virtualenv' in the same rule as they are now defined as mutual exclusive: 
- [Reference in Ansible Documentation](http://docs.ansible.com/ansible/pip_module.html#options)
- [Commit](https://github.com/ansible/ansible-modules-core/pull/3074/commits/24c6b269c93464152d1bb4b58ccbbff2b1425867) containing this change in ansible-modules-core.

**Comment by fdemmer** [comment]
thanks, looks redundant anyway.
