### ISSUE TITLE
Run supervisor tasks with correct utf-8 LANG env settings

### ISSUE THREAD

**Issue by dpratter** [fdemmer/ansible_roles#6]
If run with supervisor and gunicorn, Django file uploads seem to fail with `UnicodeEncodeErrors` if filename contains unicode characters. This is caused by a strange supervisor bug, where supervisor does not use correct utf-8 LANG env settings.

Can be solved by explicitly adding correct LANG variables 
`LANG=en_US.UTF-8, LC_ALL=en_US.UTF-8, LC_LANG=en_US.UTF-8`
to `ENVIRONMENT` section in `service_group.conf.j2` template.

**Comment by fdemmer** [comment]
Thank you!
